# =============================================================================
# SYNAPSE Connector Security Tests
# =============================================================================
# OWASP ZAP configuration for penetration testing SYNAPSE connectors.
# 
# Attack Surfaces:
#   - HTTP Connector: SSRF, injection, auth bypass
#   - Slack Connector: Token exposure, message injection
#   - GitHub Connector: Token exposure, workflow injection
#   - Custom Connectors: Input validation, sandboxing
#
# Prerequisites:
#   - OWASP ZAP 2.14+ installed
#   - SYNAPSE running on target URL
#   - Test tenant configured
#
# Usage:
#   zap-cli quick-scan -c synapse-connector-tests.yaml -t http://synapse:8084
#   OR
#   docker run -v $(pwd):/zap/wrk owasp/zap2docker-stable zap-full-scan.py \
#     -t http://synapse:8084 -c synapse-connector-tests.yaml
#
# =============================================================================

env:
  contexts:
    - name: "SYNAPSE API"
      url: "${SYNAPSE_URL:-http://localhost:8084}"
      includePaths:
        - ".*api/v1/connectors.*"
        - ".*api/v1/actions.*"
        - ".*api/v1/tools.*"
        - ".*api/v1/workflows.*"
      excludePaths:
        - ".*actuator.*"
        - ".*swagger.*"
      authentication:
        type: "header"
        header: "X-Tenant-ID"
        value: "test-tenant"
      technology:
        include:
          - "Java"
          - "Spring"

jobs:
  # ==========================================================================
  # HTTP Connector Tests
  # ==========================================================================
  - type: activeScan
    name: "HTTP Connector - SSRF Detection"
    target: "${SYNAPSE_URL}/api/v1/connectors/http/execute"
    parameters:
      method: POST
      body: |
        {
          "url": "http://internal-service:8080/admin",
          "method": "GET"
        }
    rules:
      - id: 40012  # SSRF
        threshold: LOW
      - id: 90018  # Server Side Request Forgery (SSRF)
        threshold: LOW

  - type: activeScan
    name: "HTTP Connector - URL Injection"
    target: "${SYNAPSE_URL}/api/v1/connectors/http/execute"
    parameters:
      method: POST
      injectionPoints:
        - body.url
        - body.headers.*
    rules:
      - id: 40026  # Cross Site Scripting (Reflected)
        threshold: MEDIUM
      - id: 90017  # XSLT Injection
        threshold: LOW

  - type: activeScan
    name: "HTTP Connector - Header Injection"
    target: "${SYNAPSE_URL}/api/v1/connectors/http/execute"
    parameters:
      method: POST
      body: |
        {
          "url": "http://httpbin.org/headers",
          "method": "GET",
          "headers": {
            "X-Injected": "test\r\nX-Evil: header"
          }
        }
    rules:
      - id: 10015  # HTTP Response Header Injection
        threshold: LOW

  - type: activeScan
    name: "HTTP Connector - Auth Bypass"
    target: "${SYNAPSE_URL}/api/v1/connectors/http/execute"
    parameters:
      method: POST
      skipAuth: true
    rules:
      - id: 10011  # Cookie without HttpOnly flag
        threshold: MEDIUM
      - id: 10010  # Cookie without Secure flag
        threshold: MEDIUM

  # ==========================================================================
  # Action Execution Security Tests
  # ==========================================================================
  - type: activeScan
    name: "Action Execution - Input Validation"
    target: "${SYNAPSE_URL}/api/v1/actions"
    parameters:
      method: POST
      body: |
        {
          "toolId": "test-tool",
          "input": {
            "command": "; rm -rf /",
            "file": "../../../etc/passwd"
          }
        }
    rules:
      - id: 90020  # Remote OS Command Injection
        threshold: LOW
      - id: 6  # Path Traversal
        threshold: LOW

  - type: activeScan
    name: "Action Execution - Privilege Escalation"
    target: "${SYNAPSE_URL}/api/v1/actions"
    parameters:
      method: POST
      injectionPoints:
        - body.toolId
        - body.tenantId
    rules:
      - id: 10108  # Insecure Direct Object References
        threshold: MEDIUM

  - type: activeScan
    name: "Action Execution - SQL Injection"
    target: "${SYNAPSE_URL}/api/v1/actions"
    parameters:
      method: POST
      injectionPoints:
        - body.input.*
    rules:
      - id: 40018  # SQL Injection
        threshold: LOW
      - id: 40019  # SQL Injection (MySQL)
        threshold: LOW
      - id: 40020  # SQL Injection (PostgreSQL)
        threshold: LOW

  # ==========================================================================
  # Tool Registry Security Tests
  # ==========================================================================
  - type: activeScan
    name: "Tool Registry - Code Injection"
    target: "${SYNAPSE_URL}/api/v1/tools"
    parameters:
      method: POST
      body: |
        {
          "name": "malicious-tool",
          "manifest": {
            "handler": "eval(require('child_process').execSync('id'))"
          }
        }
    rules:
      - id: 90020  # Remote OS Command Injection
        threshold: LOW
      - id: 10202  # Absence of Anti-CSRF Tokens
        threshold: MEDIUM

  - type: activeScan
    name: "Tool Registry - Schema Bypass"
    target: "${SYNAPSE_URL}/api/v1/tools"
    parameters:
      method: POST
      injectionPoints:
        - body.manifest.*
    rules:
      - id: 90034  # Cloud Metadata Attack
        threshold: LOW

  # ==========================================================================
  # Slack Connector Tests
  # ==========================================================================
  - type: activeScan
    name: "Slack Connector - Token Exposure"
    target: "${SYNAPSE_URL}/api/v1/connectors/slack"
    parameters:
      method: GET
    rules:
      - id: 10017  # Cross-Domain JavaScript Source File Inclusion
        threshold: MEDIUM
      - id: 10024  # Information Disclosure - Sensitive Information
        threshold: LOW

  - type: activeScan
    name: "Slack Connector - Message Injection"
    target: "${SYNAPSE_URL}/api/v1/connectors/slack/send"
    parameters:
      method: POST
      body: |
        {
          "channelId": "C12345",
          "message": "<script>alert('xss')</script>"
        }
    rules:
      - id: 40012  # Cross Site Scripting (Reflected)
        threshold: MEDIUM

  # ==========================================================================
  # GitHub Connector Tests
  # ==========================================================================
  - type: activeScan
    name: "GitHub Connector - Token Exposure"
    target: "${SYNAPSE_URL}/api/v1/connectors/github"
    parameters:
      method: GET
    rules:
      - id: 10024  # Information Disclosure - Sensitive Information
        threshold: LOW

  - type: activeScan
    name: "GitHub Connector - Workflow Injection"
    target: "${SYNAPSE_URL}/api/v1/connectors/github/dispatch"
    parameters:
      method: POST
      body: |
        {
          "owner": "test",
          "repo": "test",
          "workflow": "../../../.github/workflows/malicious.yml",
          "inputs": {
            "cmd": "$(whoami)"
          }
        }
    rules:
      - id: 6  # Path Traversal
        threshold: LOW
      - id: 90020  # Remote OS Command Injection
        threshold: LOW

  # ==========================================================================
  # Rate Limiting & DoS Tests
  # ==========================================================================
  - type: activeScan
    name: "Rate Limit Bypass"
    target: "${SYNAPSE_URL}/api/v1/actions"
    parameters:
      method: POST
      headers:
        X-Forwarded-For: "192.168.1.${random}"
    repeat: 100
    rules:
      - id: 10048  # Rate Limiting Not Implemented
        threshold: MEDIUM

  # ==========================================================================
  # Authentication & Authorization Tests
  # ==========================================================================
  - type: activeScan
    name: "Missing Authentication"
    target: "${SYNAPSE_URL}/api/v1/connectors"
    parameters:
      method: GET
      skipAuth: true
    rules:
      - id: 10010  # Cookie without Secure flag
        threshold: MEDIUM
      - id: 10020  # Access Control Testing
        threshold: HIGH

  - type: activeScan
    name: "Tenant Isolation"
    target: "${SYNAPSE_URL}/api/v1/actions"
    parameters:
      method: GET
      headers:
        X-Tenant-ID: "other-tenant"
    rules:
      - id: 10108  # Insecure Direct Object References
        threshold: HIGH

# =============================================================================
# Custom Rules for SYNAPSE
# =============================================================================
customRules:
  - id: 100001
    name: "SYNAPSE SSRF via HTTP Connector"
    description: "Detects potential SSRF via HTTP connector URL parameter"
    risk: HIGH
    pattern: "(localhost|127\\.0\\.0\\.1|10\\.|172\\.16\\.|192\\.168\\.|internal|metadata)"
    target: "RESPONSE"

  - id: 100002
    name: "Connector Token Exposure"
    description: "Detects exposure of connector tokens/secrets in responses"
    risk: CRITICAL
    pattern: "(xox[baprs]-|ghp_|gho_|github_pat_|sk-|SLACK_|GITHUB_)"
    target: "RESPONSE"

  - id: 100003
    name: "Action Command Injection"
    description: "Detects command injection patterns in action inputs"
    risk: HIGH
    pattern: "(;|\\||`|\\$\\(|&&|>>|<<)"
    target: "REQUEST"

# =============================================================================
# Reporting Configuration
# =============================================================================
reporting:
  template: "traditional-html"
  outputFile: "synapse-security-report.html"
  includedConfidences:
    - CONFIRMED
    - HIGH
    - MEDIUM
    - LOW
  includedRisks:
    - HIGH
    - MEDIUM
    - LOW
    - INFORMATIONAL

